name: battlesnake-rust
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: jbkerry/battlesnake-rust
  http_port: 8080
  name: battlesnake-rust